#
# Copyright (C) 2012 Isaac Moore <rmsy@me.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
name: AlertAFK
version: 0.1
description: Plugin to respond to the mentioning of AFK players in chat.
load: POSTWORLD
author: Isaac Moore <rmsy@me.com>
website: http://rmsy.github.com/
database: false
main: com.github.rmsy.alertafk.AlertAFK
commands:
  afk:
    description: 'Used to set the AFK status and message.'
    usage: 'Usage: /<command> AFK message'
    aliases:
      - a
      - away